// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// Copyright (c) 2024-2026 TripleACS Pty Ltd t/a 2pi Software

import { useState, useEffect } from 'react';
import { invoke } from '@tauri-apps/api/core';
import { Check, X } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import DOMPurify from 'dompurify';
import i18n from '../i18n';
import type { FieldValue, FieldType } from '../types';
import { humaniseKey } from '../utils/humanise';
import { FileField } from './FileField';

// HTML is generated by the Rust markdown renderer and sanitized with DOMPurify below.
const MARKDOWN_PURIFY_CONFIG: Parameters<typeof DOMPurify.sanitize>[1] = {
  ALLOWED_URI_REGEXP: /^(?:(?:(?:f|ht)tps?|mailto|tel|callto|sms|cid|xmpp):|data:image\/|[^a-z]|[a-z+.\-]+(?:[^a-z+.\-:]|$))/i,
};

function MarkdownField({ noteId, text }: { noteId: string; text: string }) {
  const [html, setHtml] = useState<string | null>(null);

  useEffect(() => {
    invoke<string>('render_markdown_field', { noteId, text })
      .then(setHtml)
      .catch(() => setHtml(null));
  }, [noteId, text]);

  if (html === null) {
    return <p className="whitespace-pre-wrap break-words">{text}</p>;
  }
  // Safe: server-rendered markdown, DOMPurify-sanitized before injection.
  const safeHtml = DOMPurify.sanitize(html, MARKDOWN_PURIFY_CONFIG);
  // eslint-disable-next-line react/no-danger
  return <div dangerouslySetInnerHTML={{ __html: safeHtml }} />;
}

function NoteLinkDisplay({ noteId }: { noteId: string }) {
  const [title, setTitle] = useState<string | null>(null);

  useEffect(() => {
    invoke<{ id: string; title: string }>('get_note', { noteId })
      .then(n => setTitle(n.title))
      .catch(() => setTitle('(deleted)'));
  }, [noteId]);

  if (title === null) return <span>…</span>;

  return (
    <a
      className="kn-view-link text-primary underline cursor-pointer"
      data-note-id={noteId}
    >
      {title}
    </a>
  );
}

interface FieldDisplayProps {
  fieldName: string;
  fieldType: FieldType;
  value: FieldValue;
  max?: number;
  noteId: string;
}

function FieldDisplay({ fieldName, fieldType, value, max = 5, noteId }: FieldDisplayProps) {
  const { t } = useTranslation();
  const renderValue = () => {
    if ('Number' in value && fieldType === 'rating') {
      const starCount = max > 0 ? max : 5;
      const filled = Math.min(Math.round(value.Number), starCount);
      if (filled === 0) return <p className="text-muted-foreground italic">{t('fields.notRated')}</p>;
      const stars = '★'.repeat(filled) + '☆'.repeat(Math.max(0, starCount - filled));
      return <p className="text-yellow-400 text-lg leading-none">{stars}</p>;
    }
    if ('Text' in value) {
      if (fieldType === 'textarea') {
        return <MarkdownField noteId={noteId} text={value.Text} />;
      }
      return <p className="whitespace-pre-wrap break-words">{value.Text}</p>;
    } else if ('Number' in value) {
      return <p>{value.Number.toLocaleString(i18n.language)}</p>;
    } else if ('Boolean' in value) {
      return (
        <span className="inline-flex items-center" aria-label={value.Boolean ? t('fields.yesLabel') : t('fields.noLabel')}>
          {value.Boolean
            ? <Check size={18} className="text-green-500" aria-hidden="true" />
            : <X size={18} className="text-red-500" aria-hidden="true" />}
        </span>
      );
    } else if ('Email' in value) {
      return <a href={`mailto:${value.Email}`} className="text-primary underline">{value.Email}</a>;
    } else if ('Date' in value) {
      if (value.Date === null) return <p className="text-muted-foreground italic">{t('fields.notSet')}</p>;
      const formatted = new Date(`${value.Date}T00:00:00`).toLocaleDateString(i18n.language, {
        year: 'numeric', month: 'long', day: 'numeric',
      });
      return <p>{formatted}</p>;
    }
    if (fieldType === 'note_link') {
      if (!value || !('NoteLink' in value) || (value as { NoteLink: string | null }).NoteLink === null) {
        return <span>—</span>;
      }
      return <NoteLinkDisplay noteId={(value as { NoteLink: string | null }).NoteLink as string} />;
    }
    if (fieldType === 'file') {
      const fileId = value && 'File' in value ? (value as { File: string | null }).File : null;
      return (
        <FileField
          attachmentId={fileId}
          allowedTypes={[]}
          isEditing={false}
          noteId={noteId}
          onValueChange={() => {}}
        />
      );
    }
    return <span className="text-muted-foreground italic">{t('fields.unknown')}</span>;
  };

  return (
    <>
      <dt className="text-sm font-medium text-muted-foreground self-start pt-0.5 whitespace-nowrap">
        {humaniseKey(fieldName)}
      </dt>
      <dd className="m-0 text-foreground">
        {renderValue()}
      </dd>
    </>
  );
}

export default FieldDisplay;
