//! Tauri build script.
//!
//! 1. Runs Tauri's required code-generation step.
//! 2. Scans `../src/i18n/locales/*.json` and generates `$OUT_DIR/locales_generated.rs`,
//!    which embeds all locale JSON content as static string literals. Adding a new
//!    language requires only dropping a JSON file in the locales directory.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    tauri_build::build();

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let locales_dir = Path::new(&manifest_dir).join("../src/i18n/locales");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let out_path = Path::new(&out_dir).join("locales_generated.rs");

    // Re-run this script if the locales directory itself changes (new file added/removed).
    println!("cargo:rerun-if-changed=../src/i18n/locales");

    let mut entries: Vec<(String, String)> = Vec::new();

    let read_dir = fs::read_dir(&locales_dir)
        .unwrap_or_else(|e| panic!("Cannot read locales directory {}: {e}", locales_dir.display()));
    for entry in read_dir.flatten() {
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) == Some("json") {
            if let Some(lang) = path.file_stem().and_then(|s| s.to_str()) {
                // Re-run if this specific file changes.
                println!("cargo:rerun-if-changed={}", path.display());
                let content = fs::read_to_string(&path)
                    .unwrap_or_else(|e| panic!("Failed to read {}: {e}", path.display()));
                entries.push((lang.to_string(), content));
            }
        }
    }

    // Sort for deterministic output.
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut code = String::from("// Auto-generated by build.rs \u{2014} do not edit.\n");
    code.push_str("pub static LOCALES: &[(&str, &str)] = &[\n");
    for (lang, content) in &entries {
        // Escape the JSON content for embedding as a Rust string literal.
        let escaped = content
            .replace('\\', "\\\\")
            .replace('"', "\\\"")
            .replace('\n', "\\n")
            .replace('\r', "");
        code.push_str(&format!("    (\"{lang}\", \"{escaped}\"),\n"));
    }
    code.push_str("];\n");

    fs::write(&out_path, &code).expect("Failed to write locales_generated.rs");
}
